# when using oh-my-szh, turn off COMPLETION_WAITING_DOTS or you might screw up 
# your newlines on tab completion
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=false
POWERLEVEL9K_DISABLE_RPROMPT=false

#POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
#POWERLEVEL9K_SHORTEN_DELIMITER=""
#POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"

POWERLEVEL9K_TIME_BACKGROUND='239'
POWERLEVEL9K_TIME_FOREGROUND='010'

POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='232'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='003'
POWERLEVEL9K_DIR_HOME_FOREGROUND='232'
POWERLEVEL9K_DIR_HOME_BACKGROUND='011'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='232'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='010'

POWERLEVEL9K_HISTORY_BACKGROUND='235'
POWERLEVEL9K_HISTORY_FOREGROUND='240'

POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=true

POWERLEVEL9K_VCS_CLEAN_FOREGROUND='016'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='002'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='016'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='136'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='016'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='124'
#POWERLEVEL9K_VCS_GIT_HOOKS=(vcs-detect-changes git-untracked git-aheadbehind git-stash git-remotebranch git-tagname)
POWERLEVEL9K_VCS_GIT_HOOKS=(vcs-detect-changes git-untracked git-aheadbehind git-stash git-remotebranch)

POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND='237'
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='034'

POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%K{white}%k"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%K{239}%F{010} %f%k%K{010}%F{239}\ue0b0%f%F{010}%k\ue0b0%f "

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(time history dir detect_virt)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs command_execution_time vcs context)
